apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempphonemanagement
  labels:
    app: tempphonemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempphonemanagement
  template:
    metadata:
      labels:
        app: tempphonemanagement
    spec:
      containers:
        - name: tempphonemanagement
          image: "username/tempphonemanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
