apiVersion: v1
kind: Service
metadata:
  name: tempphonemanagement
  labels:
    app: tempphonemanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: tempphonemanagement