---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostphone
  labels:
    app: lostphone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostphone
  template:
    metadata:
      labels:
        app: lostphone
    spec:
      containers:
        - name: lostphone
          image: username/lostphone:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonemanagement
  labels:
    app: phonemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonemanagement
  template:
    metadata:
      labels:
        app: phonemanagement
    spec:
      containers:
        - name: phonemanagement
          image: username/phonemanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempphonemanagement
  labels:
    app: tempphonemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempphonemanagement
  template:
    metadata:
      labels:
        app: tempphonemanagement
    spec:
      containers:
        - name: tempphonemanagement
          image: username/tempphonemanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: lostphone
  labels:
    app: lostphone
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: lostphone


---


apiVersion: v1
kind: Service
metadata:
  name: phonemanagement
  labels:
    app: phonemanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: phonemanagement


---


apiVersion: v1
kind: Service
metadata:
  name: tempphonemanagement
  labels:
    app: tempphonemanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: tempphonemanagement

